name: Primitive component
description: Propose or modify a Lattice primitive.
title: "[Primitive]: "
labels: ["type:primitive", "area:primitives"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the primitive and why it belongs in Lattice.
    validations:
      required: true
