name: Primitive component
description: Propose or modify a Lattice primitive.
title: "[Primitive]: "
labels: ["type:primitive", "area:primitives"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the primitive and why it belongs in Lattice.
    validations:
      required: true
  - type: textarea
    id: role
    attributes:
      label: Intended role in Lattice
      description: Why does this belong in Lattice rather than higher in the product stack?
    validations:
      required: true
  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: Props, variants, sizes, controlled/uncontrolled behavior.
    validations:
      required: true
