name: Spike / exploration
description: Research, investigation, or proof-of-concept work.
title: "[Spike]: "
labels: ["type:spike"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question to answer
      description: The specific uncertainty this spike addresses.
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: Time, scope, or technical limits.
    validations:
      required: true
  - type: textarea
    id: outofscope
    attributes:
      label: Out of scope
      description: What this spike explicitly will not attempt.
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of done
      description: What knowledge or decision is expected at completion.
    validations:
      required: true
  - type: checkboxes
    id: conclusion
    attributes:
      label: Spike outcome
      options:
        - label: Findings will be documented in the issue before closing
          required: true
